$background = rgb(18191A)
$foreground = rgb(F7EEFC)
$color0 = rgb(3F4041)
$color1 = rgb(414050)
$color2 = rgb(686072)
$color3 = rgb(696377)
$color4 = rgb(AB6D95)
$color5 = rgb(998AA5)
$color6 = rgb(AD9BB9)
$color7 = rgb(EBDFF3)
$color8 = rgb(A49CAA)
$color9 = rgb(57566A)
$color10 = rgb(8B8098)
$color11 = rgb(8C849F)
$color12 = rgb(E491C7)
$color13 = rgb(CDB8DC)
$color14 = rgb(E7CFF7)
$color15 = rgb(EBDFF3)
